/* Thin distributed-runtime aggregation unit; implementation lives in parts/. */
#include "parts/00_protocol_and_transport.inc"
#include "parts/01_wire_and_handshake.inc"
#include "parts/02_coordinator_routing.inc"
#include "parts/03_output_and_prefill_pipeline.inc"
#include "parts/04_generation_clients_and_snapshots.inc"
#include "parts/05_kv_payload.inc"
#include "parts/06_sessions_and_worker_frames.inc"
#include "parts/07_route_forwarding.inc"
#include "parts/08_worker_sessions_and_work.inc"
#include "parts/09_worker_queue_and_cli.inc"
