/* Thin aggregation unit. Implementation is split by subsystem in parts/. */
#include "parts/00_runtime_state.inc"
#include "parts/01_graph_capture.inc"
#include "parts/02_tensor_memory.inc"
#include "parts/03_model_cache.inc"
#include "parts/04_normalization_linear.inc"
#include "parts/05_attention_score.inc"
#include "parts/06_attention_decode.inc"
#include "parts/07_packed_indexer.inc"
#include "parts/08_q8_projection.inc"
#include "parts/09_speculative_attention.inc"
#include "parts/10_prefill_attention.inc"
#include "parts/11_moe_quantized.inc"
#include "parts/12_moe_reduction.inc"
#include "parts/13_moe_tensorcore.inc"
#include "parts/14_moe_dispatch.inc"
#include "parts/18_compat_api.inc"
